# Generated by Django 2.1.2 on 2019-02-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0004_auto_20190109_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='type',
            field=models.CharField(choices=[('MONEY', 'Monetary values with currency.'), ('EURO', 'Euro amounts.'), ('PERSON', 'Name of a person or family.'), ('LOCATION', 'Name of geographical or political locations.'), ('ORGANIZATION', 'Any organizational entity.'), ('PERCENT', 'Percentage amounts.'), ('L_STKHOLDER', ''), ('L_ACTION', ''), ('L_MATTER_I_D', ''), ('L_AMOUNT_I_D', ''), ('L_RULING', '')], help_text='Entity type', max_length=12),
        ),
    ]
